### ISSUE TITLE
zbackup CentOS 5 i386

### ISSUE THREAD

**Issue by 33hops** [zbackup/zbackup#106]
I am trying to compile zbackup for centos 5 i386. After having installed all dependencies I get this error at the time to compile with make. ./configure runs fine.
In fact I have not seen much info nor .rpm packages for 32 bit, can zbackup be compiled for a 32 bit environment? or are there any coding constraints that make it unfeasible

/root/software/zbackup-1.4.4/compression.cc: In member function âvirtual bool Compression::NoStreamAndUnknownSizeDecoder::isCompleteInput(const char*, size_t)â:
/root/software/zbackup-1.4.4/compression.cc:325: error: âle32tohâ was not declared in this scope
/root/software/zbackup-1.4.4/compression.cc: In member function âvirtual size_t Compression::NoStreamAndUnknownSizeDecoder::suggestOutputSize(const char*, size_t)â:
/root/software/zbackup-1.4.4/compression.cc:339: error: âle32tohâ was not declared in this scope
/root/software/zbackup-1.4.4/compression.cc: In member function âvirtual bool Compression::NoStreamAndUnknownSizeDecoder::doProcess(const char*, size_t, char*, size_t, size_t&)â:
/root/software/zbackup-1.4.4/compression.cc:353: error: âle32tohâ was not declared in this scope
/root/software/zbackup-1.4.4/compression.cc: In member function âvirtual bool Compression::NoStreamAndUnknownSizeEncoder::doProcess(const char*, size_t, char*, size_t, size_t&)â:
/root/software/zbackup-1.4.4/compression.cc:421: error: âhtole32â was not declared in this scope
make[2]: *** [CMakeFiles/zbackup.dir/compression.cc.o] Error 1
make[1]: *** [CMakeFiles/zbackup.dir/all] Error 2
make: *** [all] Error 2

**Comment by Am1GO** [comment]
EL5 is EOL, you know?

Anyway I'll try to see what can I do.

2015-12-06 19:37 GMT+03:00 33HOPS <notifications@github.com>:

> I am trying to compile zbackup for centos 5 i386. After having installed
> all dependencies I get this error at the time to compile with make.
> ./configure runs fine.
>
> /root/software/zbackup-1.4.4/compression.cc: In member function âvirtual
> bool Compression::NoStreamAndUnknownSizeDecoder::isCompleteInput(const char
>
> *, size_t)â: /root/software/zbackup-1.4.4/compression.cc:325: error:
> âle32tohâ was not declared in this scope
> /root/software/zbackup-1.4.4/compression.cc: In member function âvirtual
> size_t Compression::NoStreamAndUnknownSizeDecoder::suggestOutputSize(const
> char*, size_t)â:
> /root/software/zbackup-1.4.4/compression.cc:339: error: âle32tohâ was not
> declared in this scope
> /root/software/zbackup-1.4.4/compression.cc: In member function âvirtual
> bool Compression::NoStreamAndUnknownSizeDecoder::doProcess(const char*,
> size_t, char*, size_t, size_t&)â:
> /root/software/zbackup-1.4.4/compression.cc:353: error: âle32tohâ was not
> declared in this scope
> /root/software/zbackup-1.4.4/compression.cc: In member function âvirtual
> bool Compression::NoStreamAndUnknownSizeEncoder::doProcess(const char*,
> size_t, char*, size_t, size_t&)â:
> /root/software/zbackup-1.4.4/compression.cc:421: error: âhtole32â was not
> declared in this scope
> make[2]: *** [CMakeFiles/zbackup.dir/compression.cc.o] Error 1
> make[1]: *** [CMakeFiles/zbackup.dir/all] Error 2
> make: *** [all] Error 2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zbackup/zbackup/issues/106>.
>



-- 
Kind regards,
Vladimir.

**Comment by 33hops** [comment]
I know, but zbackup is such a versatile tool that may be suitable to be included in appliances and stripped down environments where older distributions may be the base OS, like in my case. I'll appreciate any effort from your part, but don't want to take much of your time.

**Comment by Am1GO** [comment]
Fixed in https://github.com/zbackup/zbackup/tree/stable-1.4 branch.
Also fixed in master branch but I've not pushed it to this repository yet.

Can you confirm it works ok for you?

**Comment by 33hops** [comment]
Yeap, got it compiled, thanks a lot.
