### ISSUE TITLE
Big CPU load without reason

### ISSUE THREAD

**Issue by korjavin** [zbackup/zbackup#13]
I have to use  zbackup repo long time, now it has 336 backups.

It was works fine, and full backup take about 2 hours.

Here is graph cpu load from my server:
![chart2 php](https://cloud.githubusercontent.com/assets/148765/3513648/e01fe3ca-06c4-11e4-9720-878199b37a9c.png)

Last day it take abnormal CPU usage, and after long time I killed zbackup proccess.

I tryed again, and again it eat CPU and not finished for 4+ hours.

No idea, where I should search the answer.

A lot of disk space, all seems correct, nothing changed.

What I should check? 
Is there any internal restrictions?

**Comment by sanmai** [comment]
One of the reasons these things happening could be cache pollution with source files, and consequent  memory pressure. It could be avoided by telling the reading process to skip the cache.

     nocache tar c /my/precious/data | zbackup backup ...

Look for nocache in Debian repos, or read about it [here on GitHub](https://github.com/Feh/nocache).

**Comment by korjavin** [comment]
Thank you!
