### ISSUE TITLE
Feature request: no compression

### ISSUE THREAD

**Issue by avollmerhaus** [zbackup/zbackup#145]
I'm using ZFS to store zbackup data, at the moment I'm using a separate subvol with `compression=off` to avoid the overhead of both lzma and lz4 (as that is what my ZFS pool uses otherwise).

Adding something like `--no-compression` would enable users (at least those on ZFS) to use lz4 or gzip through the filesystem and avoid the need for a separate subvol with `compression=off`.

Many thanks for this great tool!

**Comment by mknjc** [comment]
This is already in zbackup `-o bundle.compression_method=zero` is your friend.

**Comment by avollmerhaus** [comment]
Thanks, I was not aware of that. Maybe it should be be mentioned [here](https://github.com/zbackup/zbackup#compression).
