### ISSUE TITLE
Segmentation Fault while starting zbackup since 30fe01a 

### ISSUE THREAD

**Issue by gibbon-joel** [zbackup/zbackup#48]
Hi, 

I am uncertain if this is for a github issue - feel free to close it otherwise. 

Since the recent commit 30fe01a I am unable to build zbackup to work correctly on debian stable. Using a clean tree, rerunning cmake and rebuilding changes nothing. c5b821b works fine. I know that not every revision is supposed to provide a clean build, but I wanted to inform about the issue. I am not a developer but will try to provide debugging information.

I get a segmentation fault.

The following information is a first attempt in trying to help. If I can provide anything more, feel free to ask.

Platform is amd64

# CMake:
         -- The C compiler identification is GNU 4.7.2
         -- The CXX compiler identification is GNU 4.7.2
         -- Check for working C compiler: /usr/bin/gcc
         -- Check for working C compiler: /usr/bin/gcc -- works
         -- Detecting C compiler ABI info
         -- Detecting C compiler ABI info - done
         -- Check for working CXX compiler: /usr/bin/c++
         -- Check for working CXX compiler: /usr/bin/c++ -- works
         -- Detecting CXX compiler ABI info
         -- Detecting CXX compiler ABI info - done
         -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.7") 
         -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1e") 
         -- Found PROTOBUF: /usr/lib/libprotobuf.so  
         -- Looking for include file pthread.h
         -- Looking for include file pthread.h - found
         -- Looking for pthread_create
         -- Looking for pthread_create - not found.
         -- Looking for pthread_create in pthreads
         -- Looking for pthread_create in pthreads - not found
         -- Looking for pthread_create in pthread
         -- Looking for pthread_create in pthread - found
         -- Found Threads: TRUE  
         -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
         -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
         -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
         -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
         -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
         -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
         -- Found LibLZMA: /usr/include (found version "5.1.0") 
         -- Looking for lzo1x_decompress_safe in /usr/lib/x86_64-linux-gnu/liblzo2.so
         -- Looking for lzo1x_decompress_safe in /usr/lib/x86_64-linux-gnu/liblzo2.so - found
         -- Looking for lzo1x_1_compress in /usr/lib/x86_64-linux-gnu/liblzo2.so
         -- Looking for lzo1x_1_compress in /usr/lib/x86_64-linux-gnu/liblzo2.so - found
         -- Found LibLZO: /usr/include (found version "2.06") 
         -- Looking for unw_getcontext
         -- Looking for unw_getcontext - found
         -- Looking for unw_init_local
         -- Looking for unw_init_local - found
         -- Found LibUnwind: /usr/include (found version "0.99") 
         -- Configuring done
         -- Generating done
         -- Build files have been written to: /usr/src/zbackup_test  

# Some compiler warnings while building:
        /usr/src/zbackup_test/zbackup_base.cc: In member function ‘ExtendedStorageInfo ZBackupBase::loadExtendedStorageInfo(const EncryptionKey&)’:
        /usr/src/zbackup_test/zbackup_base.cc:160:14: warning: ‘google::protobuf::uint32 StorageInfo::chunk_max_size() const’ is deprecated (declared at  /usr/src/zbackup_test/zbackup.pb.h:1710) [-Wdeprecated-declarations]
        /usr/src/zbackup_test/zbackup_base.cc:161:14: warning: ‘google::protobuf::uint32 StorageInfo::bundle_max_payload_size() const’ is deprecated (declared at  /usr/src/zbackup_test/zbackup.pb.h:1732) [-Wdeprecated-declarations]
        /usr/src/zbackup_test/zbackup_base.cc:163:14: warning: ‘const string& StorageInfo::default_compression_method() const’ is deprecated (declared at          /usr/src/zbackup_test/zbackup.pb.h:1785) [-Wdeprecated-declarations]

# ldd ./zbackup
        linux-vdso.so.1 =>  (0x00007fffe57ff000)
        libprotobuf.so.7 => /usr/lib/libprotobuf.so.7 (0x00007f9c2398d000)
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f9c2372d000)
        libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f9c23334000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9c23118000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9c22f01000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f9c22cdd000)
        liblzo2.so.2 => /usr/lib/x86_64-linux-gnu/liblzo2.so.2 (0x00007f9c22abc000)
        libunwind.so.7 => /usr/lib/libunwind.so.7 (0x00007f9c228a3000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9c2259b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9c22319000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9c22103000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9c21d76000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9c21b72000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9c23c94000)

# gdb output
        GNU gdb (GDB) 7.4.1-debian
        Copyright (C) 2012 Free Software Foundation, Inc.
        License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
        This is free software: you are free to change and redistribute it.
        There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
        and "show warranty" for details.
        This GDB was configured as "x86_64-linux-gnu".
        For bug reporting instructions, please see:
        <http://www.gnu.org/software/gdb/bugs/>...
        Reading symbols from /usr/src/zbackup_test/zbackup...(no debugging symbols found)...done.
        (gdb) run
        Starting program: /usr/src/zbackup_test/zbackup 
        [Thread debugging using libthread_db enabled]
        Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
        
        Program received signal SIGSEGV, Segmentation fault.
        0x0000000000423c75 in _GLOBAL__sub_I__ZN12ConfigHelper13defaultConfigE ()

**Comment by Am1GO** [comment]
You could ignore all warnings related to StorageInfo. It's because I've deprecated some fields in StorageInfo message.

Please provide following information so I could try to reproduce this bug:
* Your Debian version
* Full backtrace of your debug build

You can get full backtrace of debug build following those steps:
(In zbackup source directory)
* ```git pull; git merge master```
* ```unset CFLAGS CXXFLAGS CCFLAGS CPPFLAGS FFLAGS```
*  ```mkdir -p objdir; pushd objdir/; cmake28 -DCMAKE_BUILD_TYPE=Debug ../; popd; make -C objdir```
* ```echo -e 'r\nbt f\nq' > gdb_cmds```
* ```gdb objdir/zbackup -x gdb_cmds```

Output of last command is a full backtrace of your debug build.

**Comment by gibbon-joel** [comment]
Sure,

Debian Version is 7.8 with the following sources-list:
> deb http://ftp.de.debian.org/debian/ wheezy main non-free contrib
> deb http://security.debian.org/ wheezy/updates main contrib non-free
> deb http://ftp.de.debian.org/debian/ wheezy-updates main contrib non-free
> deb http://http.debian.net/debian wheezy-backports main

find a dpkg -l for the machine here: http://bin.jjim.de/paste/I99ucBhjknlkOd+V#EtCkIGV75ffyuvrsCKwZ-htAMPKVroNVL6qFKhygWLA

Your oneliner does not quite work since cmake always creates the files in my tree root. 

Nonetheless - here is the backstrace. I hope it helps.

        Reading symbols from /usr/src/zbackup_test/zbackup...done.
        [Thread debugging using libthread_db enabled]
        Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
        [DEBUG] at Config( config.cc:151 ): 6Config is instantiated and initialized with default values
        
        Program received signal SIGSEGV, Segmentation fault.
        0x000000000045734c in ConfigInfo::chunk (this=0x6b38b0) at /usr/src/zbackup_test/zbackup.pb.h:1982
        1982      return chunk_ != NULL ? *chunk_ : *default_instance_->chunk_;
        #0  0x000000000045734c in ConfigInfo::chunk (this=0x6b38b0) at /usr/src/zbackup_test/zbackup.pb.h:1982
        No locals.
        #1  0x0000000000456d51 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /usr/src/zbackup_test/config.cc:60
        No locals.
        #2  0x0000000000457023 in _GLOBAL__sub_I__ZN12ConfigHelper13defaultConfigE () at /usr/src/zbackup_test/config.cc:557
        No locals.
        #3  0x000000000048796d in __libc_csu_init ()
        No symbol table info available.
        #4  0x00007ffff5ee8e40 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
        No symbol table info available.
        #5  0x000000000044b349 in _start ()
        No symbol table info available.
        A debugging session is active.
        
        Inferior 1 [process 27092] will be killed.

**Comment by gibbon-joel** [comment]
nevermind, I noticed I did something wrong. cmake had the paths cached.

**Comment by Am1GO** [comment]
Ok, I'll try to reproduce and fix it.

**Comment by gibbon-joel** [comment]
Thank you very much. Not only for the fix but also for this great tool :). Its just the right tool.

**Comment by px-nb** [comment]
I can confirm this bug after building the current git version on Arch Linux. GDB output looks roughly similar to what @gibbon-joel posted earlier, but can be provided if needed.

**Comment by Am1GO** [comment]
I'm developing under CentOS 6.6 and it looks like some protobuf changes in newer version.
Temporary workaround was commited.

**Comment by gibbon-joel** [comment]
Works. Thank you very much so far :) If I can do anything more, please let me know.

**Comment by Am1GO** [comment]
You can help with further bug hunting :)

**Comment by gibbon-joel** [comment]
Right on it. :)

**Comment by Am1GO** [comment]
Nah, it's not an protobuf issue, tested on F20 with protobuf-2.3.0-9 from EPEL.

**Comment by Am1GO** [comment]
Looks like gcc bug or I'm doing something wrong.
I'll continue my tests, you can see results here: https://github.com/Am1GO/gcc-testcase

**Comment by Am1GO** [comment]
Of course I'll much appreciate if you can publish your results.

**Comment by Am1GO** [comment]
According to test results it was really gcc bug.
I'll update issue status as soon as I'll receive any feedback from gcc developers.

**Comment by gibbon-joel** [comment]
Sorry for publishing them here, but I was too afraid to send a pull request for readme-md in the other project ;)

Results for the machine running debian stable (7.8) with backports (i initially reported the issue on)
      ./test.sh: line 16: 27485 Segmentation fault      ./testcase
      # g++ -v
      Using built-in specs.
      COLLECT_GCC=g++
      COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
      Target: x86_64-linux-gnu
      Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
      Thread model: posix
      gcc version 4.7.2 (Debian 4.7.2-5) 

A comparison with a debian unstable machine:
      ./test.sh: line 16: 14661 Segmentation fault      ./testcase
      # g++ -v
      Using built-in specs.
      COLLECT_GCC=g++
      COLLECT_LTO_WRAPPER=/usr/lib/gcc/i586-linux-gnu/4.9/lto-wrapper
      Target: i586-linux-gnu
      Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --with-arch-32=i586 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=i586-linux-gnu --host=i586-linux-gnu --target=i586-linux-gnu
      Thread model: posix
      gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by Am1GO** [comment]
Thank you!
BTW I have found an additional workaround: just compile with any optimization flag enabled (-O1 and above).
