### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [zbackup/zbackup#51]
I would like to point out that identifiers like "[`BACKUP_CREATOR_HH_INCLUDED__`](https://github.com/zbackup/zbackup/blob/a5c785740847ae967c99cc12a6c8c43a847cb3d0/backup_creator.hh#L4)" and "[`CHUNK_STORAGE_HH_INCLUDED__`](https://github.com/zbackup/zbackup/blob/30fe01a2a0cf563e773a4fe2433dc45f87ce945d/chunk_storage.hh#L4)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by Am1GO** [comment]
9022e1fac478e545f19a577135bd991d641f69c4

**Comment by elfring** [comment]
Thanks for your source code improvement.
