### ISSUE TITLE
Addition of a catch-all handler?

### ISSUE THREAD

**Issue by elfring** [zbackup/zbackup#52]
Would you like to add [the construct "catch(...)"](http://accu.org/index.php/journals/1706/ "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions") in the function "[main](https://github.com/zbackup/zbackup/blob/a04128961a10abc5bd3ad723892af94120f832a7/zbackup.cc#L311 "main() function")"?

**Comment by elfring** [comment]
Thanks for your small source code improvement.

**Comment by Am1GO** [comment]
Feel free to suggest any additional improvements :)
