### ISSUE TITLE
Sequential reading of the backup

### ISSUE THREAD

**Issue by brcha** [zbackup/zbackup#59]
Hi,

I took a look at your code, but I don't have enough time at the moment to dig deep into it, especially since I have no idea how protobufs work (although they do seam like something I'll look into in the near future). My question is:

would it be possible to read parts of the backup? For example - first kilobyte or 1 kb at 3 mb from the start and things like that?

If that is possible, then it would probably be easy to restore specific files from the tar, and not the entire backed up tar. Or, if some manifest file is added at the beginning of the archive (zip has that, I think), then it would be possible to make visible the entire backed up file tree using fuse, a gui frontend or something like that.

**Comment by Am1GO** [comment]
Yes, I'll implement random access in some of the future versions.
