### ISSUE TITLE
GC failing with 'Can't parse message FileHeader'

### ISSUE THREAD

**Issue by zunkree** [zbackup/zbackup#65]
zbackup version 1.4.1
gentoo linux

    ~ $ zbackup --non-encrypted gc zrepo || echo 1
    Loading index...
    Loading index file 142c784cfc57a5fd6a25bc995481ba0ffc29bee6534ebd9b... 
    Loading index file 53165df2656d04de2d24566659f30739cfc5f3cfe170d4ae... 
    Loading index file 1fe7a0b3824433fade24ddc582e02df876ba5ed359ed567a... 
    Loading index file 157eca6435071df96253d85309ab8c9070de08adf2bde9b6... 
    Loading index file 0ba93a21c483b5b62265d74b8656c0dbb2887705cbd1b9b2... 
    Index loaded.
    Using up to 40 MB of RAM as cache
    Using up to 8 thread(s) for compression
    Checking used chunks...
    Checking backup prod...
    Can't parse message FileHeader
    1

**Comment by Am1GO** [comment]
What will happen if you run
`zbackup --non-encrypted restore zrepo/backups/prod`
?

**Comment by zunkree** [comment]
`zrepo/backups/prod` is a directory, themselves backups stored in `zrepo/backups/prod/app/<backup_name>`

**Comment by Am1GO** [comment]
https://github.com/zbackup/zbackup/issues/50
