### ISSUE TITLE
CentOS 7 support

### ISSUE THREAD

**Issue by mumblez** [zbackup/zbackup#68]
Hi,

Tried installing build dependancies and building zbackup but failing to find dependancies.
Any chance you can explain how to build this for centos (7) ?

Many Thanks

**Comment by mumblez** [comment]
if it helps I installed the following and successfully built zbackup:

-cmake
-libarchive
-gcc, gcc-c++, zlib-devel, openssl-devel, protobuf-devel, lzo-devel, xz-devel

xz-devel contains dev libs for lzma
libarchive was a dependancy of cmake

running through a backup (and eventually) restore to confirm it works...

**Comment by Am1GO** [comment]
ZBackup was already present in EPEL7 [1].

[1] https://apps.fedoraproject.org/packages/zbackup

2015-03-22 21:09 GMT+03:00 Yusuf <notifications@github.com>:

> if it helps I installed the following and successfully built zbackup:
>
> -cmake
> -libarchive
> -gcc, gcc-c++, zlib-devel, openssl-devel, protobuf-devel, lzo-devel,
> xz-devel
>
> xz-devel contains dev libs for lzma
> libarchive was a dependancy of cmake
>
> running through a backup (and eventually) restore to confirm it works...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zbackup/zbackup/issues/68#issuecomment-84667957>.
>



-- 
Kind regards,
Vladimir.
