### ISSUE TITLE
error: Can't open file /usr/home/username/a_zbackup_repo/tmp/q6HhmS

### ISSUE THREAD

**Issue by bdklahn** [zbackup/zbackup#72]
I provided a reasonable fix (commit 4c73159ad5897b87478dcc1eccf3b67f95ef542d), via pull request.

It looks like a call to umask used the wrong permission settings. When the
temporary file was created with mkstemp, read and write permissions were masked
off for the owner. My FreeBSD, rightfully, followed the umask setting. I'm not sure
if/why zbackup was working for GNU/Linux systems, unless they were ignoring the
umask setting, all together. umask can be thought of as a way to REMOVE permissions.

I believe that setting the umask, in the context of temporary files, is done to
work around a security issue where some old (10+ years) c libraries' implementations
of mkstemp would create files with mode 666 (read and write for everyone).
Modern implementations create temporary files with 600 (only the owner can read
and write). So it is probably fairly safe to remove the umask call, all
together. But my commit provides a reasonable way to set the umask. It also
resets the umask to the previous setting, after the file is created.

An arguably better way, might be to explicitly set the temporary file's mode,
after creation (but before any potentially sensitive data is written to it):
e.g.
fchmod(fd, S_IRUSR | S_IWUSR );

I suppose there is an extremely slight chance (if an old mkstemp library is
used), that something/someone else writes to that temp file, after it is created,
but before the chmod. But it is also possible that the umask setting is ignored
during the file creation.

It took a while to figure this out, because the temporary folder and files disappear
before program exit (destructors in tmp_mgr.cc?). So I first thought they might
not have been created in the first place.

**Comment by jgaa** [comment]
I had the same problem on a Debian 7.8 system. The patch fixed it.

**Comment by vitalif** [comment]
+1

**Comment by Am1GO** [comment]
Sorry for that stupid umask call, it was already fixed in https://github.com/zbackup/zbackup/commit/6b0fd79da0b7d29273141c5b38fef0f38bc7eebc
