### ISSUE TITLE
Handling on low ulimit

### ISSUE THREAD

**Issue by Firefishy** [zbackup/zbackup#74]
OSX has a painfully low default file handles ulimit. (soft: 256, hard: 4096)
zbackup dies unexpectedly on larger backups if the limit is not increased...
Error is: "Can't open file /path/bundles/fe/f...."

Ideally zbackup should warn on low limit or display an error when file handles are exceeded.

**Comment by hazzl** [comment]
This is the same issue as #58. Adding a warning would be a good stop gap measure, but I actually think it would be better still to close bundles once they have been read into the cache.

**Comment by Am1GO** [comment]
Duplicate: https://github.com/zbackup/zbackup/issues/58
