### ISSUE TITLE
tar on FreeBSD

### ISSUE THREAD

**Issue by pgib** [zbackup/zbackup#75]
Both FreeBSD's build-in tar (bsdtar) and GNU tar (when installed from the ports collection) have default options which include `-f`. (These defaults can be seen by running `[g]tar --show-defaults`.) Therefore the  examples of running:

```
tar c /my/precious/data | zbackup backup ...
```

... fail with an error like:

```
tar: /dev/sa0: Cannot open: Operation not supported
```

To work around this, we can be more explicit that the "file" we should create is STDOUT:

```
tar c -f - /my/precious/data | zbackup backup ...
```

**Comment by asayers** [comment]
Just to be clear: this issue is about changing the README, right?

**Comment by pgib** [comment]
Yes, it was just a documentation issue in the README and website, too.

**Comment by Am1GO** [comment]
Feel free to contribute changes to README.
