### ISSUE TITLE
specify zbackup tmp dir

### ISSUE THREAD

**Issue by nergdron** [zbackup/zbackup#76]
I'm trying to write a little script which does encrypted zbackups to GCE's storage. I'm using gcsfuse to mount my bucket, but it doesn't support renames (due to renaming being non-atomic in S3-like datastores), and this causes problems with zbackup:

Can't rename file /mnt/gce/zbackup/tmp/SRqSBj to /mnt/gce/zbackup/bundles/4f/4f5538ccf49cc05c80a445a00644ba9b78b423b5087dfb37

It would be really useful to have a flag to specify the tmp dir zbackup uses, so I could specify something on my local filesystem, and then it could move from there to the bucket's FUSE mount when it's done. Is this possible?

**Comment by brcha** [comment]
I don't know how much free space you've got on your drive, but my approach for the similar task is making a local backup (in /home/backup/...) and then rsync-ing it to my external drive and yandex.disk online storage.
