### ISSUE TITLE
Zbackup restore output data format must be .tar?

### ISSUE THREAD

**Issue by wintonBy** [zbackup/zbackup#86]
when i use tar -zxvf xxx.tar ,there will be error message. so i must use mouse right-key  to extract here . are there some advice?

**Comment by Am1GO** [comment]
wat?

**Comment by Firefishy** [comment]
Tar files on their own are not compressed, so do not use the z option.

Eg: tar -xvf xxx.tar

**Comment by wintonBy** [comment]
@Firefishy  Thank you
