### ISSUE TITLE
do not remove tmp dir?

### ISSUE THREAD

**Issue by atimonin** [zbackup/zbackup#92]
I've tried to restore backup as root (backup is done as another user), but interrupted it in the middle.
So tmp dir wasn't removed (as I suppose), and on another backup cycle I've got:
"Can't create a temporary file in dir....."
When I have a look what was wrong with tmp dir it was already removed.
Maybe it would be better to create tmp dir once in init and never remove?

**Comment by Am1GO** [comment]
At this time I've got no plans on temporary data handling.
